import './globals.css';
import localFont from 'next/font/local';
import ClientLayout from '../components/ClientLayout';

const pretendard = localFont({
  src: './fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
});

export const metadata = {
  title: 'Clofit',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <head>
        <link rel='manifest' href='/manifest.json' />
        <meta name='theme-color' content='#ffffff' />
        <link rel='apple-touch-icon' href='/icon-196x196.png' />
        <link rel='icon' href='/favicon.ico' />
        <title>{metadata.title}</title>
        <meta name='description' content={metadata.description} />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0'
        />
      </head>

      <body className={pretendard.className}>
        {' '}
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
