services:
  backend:
    image: clofit-dev-backend:latest
    container_name: clofit-dev-backend
    networks:
      - backend-network
    # restart: unless-stopped
    expose:
      - "8080"

networks:
  backend-network:
    external: true