pipeline {
    agent any

    environment {
        TARGET_BRANCH='develop/be'
    }

    stages {
        stage('Checkout') {
            steps {
                script {
                     checkout scm
                }
            }
        }
        stage('Build') {
            steps {
                dir('backend') {
                    withCredentials([file(credentialsId: 'APPLICATION_YML', variable: 'application_yml')]) {
                        sh 'cp $application_yml ./src/main/resources/application.yml'
                    }
                    sh 'chmod +x ./gradlew'
                    // sh './gradlew clean build --no-daemon' // 디버깅을 위해 캐시하지 않기
                    // sh './gradlew test -i'
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                     sh 'docker build -t clofit-dev-backend:latest ./backend'
                }
            }
        }
        stage('Depoly') {
            steps {
                dir ('backend') {
                    script {
                         sh 'docker-compose up -d'
                    }
                }

            }
        }
        stage('Remove old Image') {
            steps {
                script {
                    sh 'docker image prune -f'
                }
            }
        }

    }
    post {
        success {
            script {
                def Author_ID = sh(script: "git show -s --pretty=%an", returnStdout: true).trim()
                def Author_Name = sh(script: "git show -s --pretty=%ae", returnStdout: true).trim()
                def Branch = sh(script: "git branch --show-current", returnStdout: true).trim()
                mattermostSend (color: 'good',
                message: "**빌드 성공** \n ${Branch} \n ${env.JOB_NAME} #${env.BUILD_NUMBER} by ${Author_ID}(${Author_Name})\n(<${env.BUILD_URL}|Details>)",
                endpoint: 'https://meeting.ssafy.com/hooks/stt1fc57q7rdubgcy9ursfrxbo',
                channel: 'B307_Build'
                )
            }
        }
        failure {
            script {
                def Author_ID = sh(script: "git show -s --pretty=%an", returnStdout: true).trim()
                def Author_Name = sh(script: "git show -s --pretty=%ae", returnStdout: true).trim()
                def Branch = sh(script: "git branch --show-current", returnStdout: true).trim()
                mattermostSend (color: 'danger',
                message: "**빌드 실패** \n ${Branch} \n ${env.JOB_NAME} #${env.BUILD_NUMBER} by ${Author_ID}(${Author_Name})\n(<${env.BUILD_URL}|Details>)",
                endpoint: 'https://meeting.ssafy.com/hooks/stt1fc57q7rdubgcy9ursfrxbo',
                channel: 'B307_Build'
                )
            }
        }
    }
}